builds:
- env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
  goarch:
    - amd64
    - arm
    - arm64
  goarm:
    - 6
    - 7
archive:
  replacements:
    darwin: macOS
    linux: Linux
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
